// One monolith with unrelated domains jammed together - merge-conflict magnet.
codeunit 50130 "CDV App Subscribers"
{
    // discount handlers...
    // shipping handlers...
    // audit handlers...
    // posting handlers...  (everything the app subscribes to, in one file)
}
